app:
  name: Phalcon Assets
  author: "Phalcon Team"
  description: "Phalcon Assets is a site designed to serve assets to Phalcon websites"
  keywords: "php, assets phalcon, phalcon php, php framework, faster php framework"
  avatar: https://assets.phalcon.io/phalcon/social/github.phalcon.assets.png
  url: https://assets.phalcon.io
  baseurl: "/"
  analytics: 'G-YDF1W191B2'
  cloudflare:
    analytics: '856753626ff24097baf12928e527a6c1'

url: https://assets.phalcon.io
social:
  email: team@phalcon.io
  facebook:
  github: phalcon
  rss: phalcon
  twitter: phalconphp

permalink: /:title

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - serve
  - updateData.php
